Find the Difference
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        sMap,tMap ={}, {}
        for sValue in s:
            if sValue not in sMap:
                sMap[sValue] = 1
            else:
                sMap[sValue] += 1
        for tValue in t:
            if tValue not in tMap:
                tMap[tValue] = 1
            else:
                tMap[tValue] += 1
        for value in t:
            if ((value not in sMap) or (tMap[value] > sMap[value])):
                return value
            
